# Generated by Backend 5.2.5 on 2025-09-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_asiento", models.CharField(max_length=20, unique=True)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("referencia", models.CharField(blank=True, max_length=100, null=True)),
                ("total_debe", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_haber", models.DecimalField(decimal_places=2, max_digits=15)),
                ("balanceado", models.BooleanField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "asiento_contable",
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabla", models.CharField(max_length=50)),
                ("registro_id", models.IntegerField()),
                ("accion", models.CharField(max_length=20)),
                ("valores_anteriores", models.JSONField(blank=True, null=True)),
                ("valores_nuevos", models.JSONField(blank=True, null=True)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "auditoria",
            },
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo_dato", models.CharField(blank=True, max_length=20, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "configuracion",
            },
        ),
        migrations.CreateModel(
            name="PeriodoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("tipo_periodo", models.CharField(max_length=20)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(blank=True, null=True)),
                ("trimestre", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(blank=True, null=True)),
                ("cerrado", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "periodo_contable",
            },
        ),
        migrations.CreateModel(
            name="TipoCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tipo", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("naturaleza", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_cuenta",
            },
        ),
        migrations.CreateModel(
            name="TransaccionOriginal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
                ("moneda", models.CharField(max_length=5)),
                (
                    "archivo_origen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fila_origen", models.IntegerField(blank=True, null=True)),
                ("procesada", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transaccion_original",
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_cuenta", models.CharField(max_length=20, unique=True)),
                ("nombre_cuenta", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("nivel", models.IntegerField()),
                ("activa", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.cuenta",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.tipocuenta",
                    ),
                ),
            ],
            options={
                "db_table": "cuenta",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(max_length=20)),
                ("activa", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cuenta_sugerida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.cuenta",
                    ),
                ),
            ],
            options={
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="DetalleAsiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "debe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "haber",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("orden", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asiento_contable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.asientocontable",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.cuenta",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_asiento",
            },
        ),
        migrations.CreateModel(
            name="ClasificacionLlm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_transaccion", models.CharField(max_length=20)),
                (
                    "confianza",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("justificacion", models.TextField(blank=True, null=True)),
                (
                    "modelo_usado",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("revisada", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.categoria",
                    ),
                ),
                (
                    "cuenta_sugerida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.cuenta",
                    ),
                ),
                (
                    "transaccion_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad.transaccionoriginal",
                    ),
                ),
            ],
            options={
                "db_table": "clasificacion_llm",
            },
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="transaccion_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilidad.transaccionoriginal",
            ),
        ),
    ]
