# Generated by Backend 5.2.5 on 2025-09-16 05:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
    ]
