# Generated by Backend 5.2.5 on 2025-09-20 01:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0002_cuenta_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
    ]
