# Generated by Backend 5.2.5 on 2025-10-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0004_alter_cuenta_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="cuenta_sugerida",
        ),
        migrations.RemoveField(
            model_name="clasificacionllm",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="Configuracion",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="auditoria",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="clasificacionllm",
            name="modelo_usado",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="activa",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="tipocuenta",
            name="created_at",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
