# Generated by Django 5.2.5 on 2025-11-19 08:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_remove_categoria_cuenta_sugerida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
