# Generated by Django 5.2.5 on 2025-11-19 08:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_cuenta_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
