# Generated by Django 5.2.5 on 2025-11-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_cuenta_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientocontable',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='referencia',
        ),
    ]
