# Generated by Django 5.2.5 on 2025-11-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_remove_asientocontable_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='permite_movimientos',
            field=models.BooleanField(default=True),
        ),
    ]
